In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using gpu : {torch.cuda.get_device_name(0)}")
else :
  print("gpu is not available. using cpu ")

GPU is available
using gpu : Tesla T4


In [ ]:
## Crw

## Creating Tensors

In [ ]:
#using empty
a = torch.empty(2,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
#using zeroes
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(3,2)

tensor([[0.0894, 0.4781],
        [0.6683, 0.6184],
        [0.4098, 0.5525]])

In [ ]:
#using seed
torch.manual_seed(90)
torch.rand(2,3)

tensor([[0.1819, 0.7287, 0.3675],
        [0.6684, 0.2857, 0.3219]])

In [ ]:
torch.manual_seed(90)
torch.rand(2,3)

tensor([[0.1819, 0.7287, 0.3675],
        [0.6684, 0.2857, 0.3219]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#other ways

#arrange
print("using arrange -->", torch.arange(0,10,2))

#using linspace
print('using linspace ', torch.linspace(0,10,10))

#using eye
print("identity matrix " , torch.eye(3,3))

#using full
print(torch.full((3,3),7))

using arrange --> tensor([0, 2, 4, 6, 8])
using linspace  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
identity matrix  tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])


## Tensor shapes


In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[   298457279758336,               3444, 187744342098837504],
        [          27984541, 249950290445467648,       150348431449]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.5514, 0.9196, 0.6360],
        [0.2115, 0.5336, 0.8606]])

## Tensor Data Types

In [ ]:
# find the datatype
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# Mathematical Opeartions

## 1.  Scalar Operations


In [ ]:
x = torch.rand(2,2)
x

tensor([[0.5171, 0.8283],
        [0.0155, 0.3812]])

In [ ]:
x + 2
x - 2
x * 3
x / 3
#int division
(x* 100) // 3

#mod
((x * 100)//3)%2

# power
x**2


tensor([[2.6739e-01, 6.8604e-01],
        [2.4087e-04, 1.4529e-01]])

## # element wise operations

In [ ]:

a = torch.rand(2,3)
b = torch.rand(2,3)


print(a)
print(b)



tensor([[0.3603, 0.2624, 0.6128],
        [0.3324, 0.4282, 0.3356]])
tensor([[0.4157, 0.0660, 0.1497],
        [0.6069, 0.0908, 0.2332]])


In [ ]:
a + b
a - b
a * b
a / b
a ** b
a % b

tensor([[0.3603, 0.0643, 0.0142],
        [0.3324, 0.0649, 0.1024]])

In [ ]:
c = torch.tensor([1,-2,3 ,-4])

In [ ]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)


tensor([2., 2., 4., 4.])

In [ ]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
torch.clamp(d, min = 2 , max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## Reduction OPeration

In [ ]:
e = torch.randint(size = (2,3), low = 1, high = 10 , dtype = torch.float32)

In [ ]:
e

tensor([[9., 3., 5.],
        [7., 7., 1.]])

In [ ]:
#sum
torch.sum(e)
#sum along columsn
torch.sum(e, dim = 0 )
#sum along rows
torch.sum(e , dim = 1 )


tensor([17., 15.])

In [ ]:
# mean
torch.mean(e)

# mean along column
torch.mean(e, dim =0 )

tensor([8., 5., 3.])

In [ ]:
# median
torch.median(e)

tensor(5.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)


tensor(1.)

In [ ]:
# product
torch.prod(e)

tensor(6615.)

In [ ]:
# std dev
torch.std(e)

tensor(2.9439)

In [ ]:
# variance
torch.var(e)

tensor(8.6667)

In [ ]:
# argmax
torch.argmax(e)

tensor(0)

In [ ]:
#argmin
torch.argmin(e)

tensor(5)

# ## Matrix Operations


In [ ]:
f = torch.randint(size = (2,3), low = 0 , high = 10 )
g = torch.randint(size = (3,2), low = 0 , high = 10 )

In [ ]:
print(f)
print(g)

tensor([[2, 8, 8],
        [0, 4, 0]])
tensor([[7, 3],
        [8, 0],
        [3, 2]])


In [ ]:
# matrix multiplication
torch.matmul(f , g)


tensor([[102,  22],
        [ 32,   0]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])


print(vector1.shape)
# dot product
# dot product

torch.dot(vector1, vector2)


torch.Size([2])


tensor(11)

In [ ]:
#transpose
torch.transpose(f,0,1)


tensor([[2, 0],
        [8, 4],
        [8, 0]])

In [ ]:
h = torch.randint(size = (3,3), low = 1, high = 10 , dtype= torch.float32)

In [ ]:
h

tensor([[3., 1., 6.],
        [2., 8., 2.],
        [7., 2., 3.]])

In [ ]:
#determinant
torch.det(h)

tensor(-244.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.0820, -0.0369,  0.1885],
        [-0.0328,  0.1352, -0.0246],
        [ 0.2131, -0.0041, -0.0902]])

## Comaprison operator

In [ ]:
i = torch.randint(size=(2,3), low=1 , high = 10 )
j = torch.randint(size=(2,3), low=1 , high = 10 )
print(i)
print(j)

tensor([[7, 5, 4],
        [6, 5, 3]])
tensor([[8, 6, 4],
        [5, 8, 4]])


In [ ]:
#greater than
i > j
# less than
i < j
## equal to
i == j
# not equal to
i != j

tensor([[ True,  True, False],
        [ True,  True,  True]])

## special functions

In [ ]:
k = torch.randint(size=(2,3), low = 1 , high = 10 , dtype= torch.float32)
k

tensor([[8., 9., 9.],
        [5., 7., 2.]])

In [ ]:
# log
torch.log(k)

tensor([[2.0794, 2.1972, 2.1972],
        [1.6094, 1.9459, 0.6931]])

In [ ]:
# exp
torch.exp(k)

tensor([[2.9810e+03, 8.1031e+03, 8.1031e+03],
        [1.4841e+02, 1.0966e+03, 7.3891e+00]])

In [ ]:
#sqrt
torch.sqrt(k)

tensor([[2.8284, 3.0000, 3.0000],
        [2.2361, 2.6458, 1.4142]])

In [ ]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9997, 0.9999, 0.9999],
        [0.9933, 0.9991, 0.8808]])

In [ ]:
#softmax
torch.softmax(k , dim = 0 )

tensor([[9.5257e-01, 8.8080e-01, 9.9909e-01],
        [4.7426e-02, 1.1920e-01, 9.1105e-04]])

In [ ]:
# relu
torch.relu(k)

tensor([[8., 9., 9.],
        [5., 7., 2.]])

## Inplace operations




```
`# This is formatted as code`
```



In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9019, 0.2153, 0.5197],
        [0.5596, 0.7077, 0.5092]])
tensor([[0.5526, 0.4243, 0.9491],
        [0.7472, 0.7512, 0.3975]])


In [ ]:
m.add_(n)

tensor([[1.4545, 0.6396, 1.4688],
        [1.3068, 1.4589, 0.9067]])

In [ ]:
m

tensor([[1.4545, 0.6396, 1.4688],
        [1.3068, 1.4589, 0.9067]])

In [ ]:
n

tensor([[0.5526, 0.4243, 0.9491],
        [0.7472, 0.7512, 0.3975]])

In [ ]:
torch.relu(m)

tensor([[1.4545, 0.6396, 1.4688],
        [1.3068, 1.4589, 0.9067]])

In [ ]:
m.relu_()

tensor([[1.4545, 0.6396, 1.4688],
        [1.3068, 1.4589, 0.9067]])

In [ ]:
m

tensor([[1.4545, 0.6396, 1.4688],
        [1.3068, 1.4589, 0.9067]])

## Copying tensor

In [ ]:
 a = torch.rand(2,3)
 a

tensor([[0.1348, 0.6183, 0.9331],
        [0.8799, 0.3005, 0.9791]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.1348, 0.6183, 0.9331],
        [0.8799, 0.3005, 0.9791]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.6183, 0.9331],
        [0.8799, 0.3005, 0.9791]])

In [ ]:
b

tensor([[0.0000, 0.6183, 0.9331],
        [0.8799, 0.3005, 0.9791]])

In [ ]:
id(a)

138367740160560

In [ ]:
id(b)

138367740160560

In [ ]:
b = a.clone()

In [ ]:
a


tensor([[0.0000, 0.6183, 0.9331],
        [0.8799, 0.3005, 0.9791]])

In [ ]:
b

tensor([[0.0000, 0.6183, 0.9331],
        [0.8799, 0.3005, 0.9791]])

In [ ]:
a[0][0]= 10

In [ ]:
a

tensor([[10.0000,  0.6183,  0.9331],
        [ 0.8799,  0.3005,  0.9791]])

In [ ]:
b

tensor([[0.0000, 0.6183, 0.9331],
        [0.8799, 0.3005, 0.9791]])

## Tensors Operations on Gpu


In [2]:
import torch

In [3]:
torch.cuda.is_available()

True

In [4]:
device = torch.device('cuda')

In [5]:
# creting a new tensor on gpu
torch.rand((2,3),device = device)

tensor([[0.5859, 0.4172, 0.3632],
        [0.7296, 0.6516, 0.2673]], device='cuda:0')

In [7]:
# moving an existing tensor to gpu
a = torch.rand(2,3)
a

tensor([[0.6186, 0.3153, 0.0330],
        [0.6405, 0.2781, 0.7196]])

In [9]:
b = a.to(device)
b

tensor([[0.6186, 0.3153, 0.0330],
        [0.6405, 0.2781, 0.7196]], device='cuda:0')

In [10]:
b + 5

tensor([[5.6186, 5.3153, 5.0330],
        [5.6405, 5.2781, 5.7196]], device='cuda:0')

In [14]:
import torch
import time

# Define the size of matrices
size = 1000

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU (if available)
if torch.cuda.is_available():
    matrix_gpu1 = matrix_cpu1.to('cuda')
    matrix_gpu2 = matrix_cpu2.to('cuda')

    # Warm-up GPU (important for fair timing)
    _ = torch.matmul(matrix_gpu1, matrix_gpu2)
    torch.cuda.synchronize()

    # Measure time on GPU
    start_time = time.time()
    result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
    torch.cuda.synchronize()  # Wait for GPU to finish before stopping timer
    gpu_time = time.time() - start_time

    print(f"Time on GPU: {gpu_time:.4f} seconds")

    # Compare performance
    print(f"\nSpeedup (CPU time / GPU time): {cpu_time / gpu_time:.2f}x")

else:
    print("⚠️ CUDA is not available. GPU test skipped.")


Time on CPU: 0.0265 seconds
Time on GPU: 0.0008 seconds

Speedup (CPU time / GPU time): 32.11x
