In [143]:
import torch
print(torch.__version__)

2.8.0+cu126


In [144]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using gpu : {torch.cuda.get_device_name(0)}")
else :
  print("gpu is not available. using cpu ")

GPU is available
using gpu : Tesla T4


In [145]:
## Crw

## Creating Tensors

In [146]:
#using empty
a = torch.empty(2,3)

In [147]:
type(a)

torch.Tensor

In [148]:
#using zeroes
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [149]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [150]:
#using rand
torch.rand(3,2)

tensor([[0.0894, 0.4781],
        [0.6683, 0.6184],
        [0.4098, 0.5525]])

In [151]:
#using seed
torch.manual_seed(90)
torch.rand(2,3)

tensor([[0.1819, 0.7287, 0.3675],
        [0.6684, 0.2857, 0.3219]])

In [152]:
torch.manual_seed(90)
torch.rand(2,3)

tensor([[0.1819, 0.7287, 0.3675],
        [0.6684, 0.2857, 0.3219]])

In [153]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [154]:
#other ways

#arrange
print("using arrange -->", torch.arange(0,10,2))

#using linspace
print('using linspace ', torch.linspace(0,10,10))

#using eye
print("identity matrix " , torch.eye(3,3))

#using full
print(torch.full((3,3),7))

using arrange --> tensor([0, 2, 4, 6, 8])
using linspace  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
identity matrix  tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])


## Tensor shapes


In [155]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [156]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [157]:
x.shape

torch.Size([2, 3])

In [158]:
torch.empty_like(x)

tensor([[   298457279758336,               3444, 187744342098837504],
        [          27984541, 249950290445467648,       150348431449]])

In [159]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [160]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [161]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.5514, 0.9196, 0.6360],
        [0.2115, 0.5336, 0.8606]])

## Tensor Data Types

In [162]:
# find the datatype
x.dtype

torch.int64

In [163]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [164]:
torch.tensor([1,2,3],dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [165]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# Mathematical Opeartions

## 1.  Scalar Operations


In [166]:
x = torch.rand(2,2)
x

tensor([[0.5171, 0.8283],
        [0.0155, 0.3812]])

In [167]:
x + 2
x - 2
x * 3
x / 3
#int division
(x* 100) // 3

#mod
((x * 100)//3)%2

# power
x**2


tensor([[2.6739e-01, 6.8604e-01],
        [2.4087e-04, 1.4529e-01]])

## # element wise operations

In [168]:

a = torch.rand(2,3)
b = torch.rand(2,3)


print(a)
print(b)



tensor([[0.3603, 0.2624, 0.6128],
        [0.3324, 0.4282, 0.3356]])
tensor([[0.4157, 0.0660, 0.1497],
        [0.6069, 0.0908, 0.2332]])


In [169]:
a + b
a - b
a * b
a / b
a ** b
a % b

tensor([[0.3603, 0.0643, 0.0142],
        [0.3324, 0.0649, 0.1024]])

In [170]:
c = torch.tensor([1,-2,3 ,-4])

In [171]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [172]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [173]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [174]:
# round
torch.round(d)


tensor([2., 2., 4., 4.])

In [175]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [176]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [177]:
torch.clamp(d, min = 2 , max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## Reduction OPeration

In [178]:
e = torch.randint(size = (2,3), low = 1, high = 10 , dtype = torch.float32)

In [179]:
e

tensor([[5., 7., 7.],
        [8., 2., 3.]])

In [180]:
#sum
torch.sum(e)
#sum along columsn
torch.sum(e, dim = 0 )
#sum along rows
torch.sum(e , dim = 1 )


tensor([19., 13.])

In [181]:
# mean
torch.mean(e)

# mean along column
torch.mean(e, dim =0 )

tensor([6.5000, 4.5000, 5.0000])

In [182]:
# median
torch.median(e)

tensor(5.)

In [183]:
# max and min
torch.max(e)
torch.min(e)


tensor(2.)

In [184]:
# product
torch.prod(e)

tensor(11760.)

In [185]:
# std dev
torch.std(e)

tensor(2.4221)

In [186]:
# variance
torch.var(e)

tensor(5.8667)

In [187]:
# argmax
torch.argmax(e)

tensor(3)

In [188]:
#argmin
torch.argmin(e)

tensor(4)

# ## Matrix Operations


In [189]:
f = torch.randint(size = (2,3), low = 0 , high = 10 )
g = torch.randint(size = (3,2), low = 0 , high = 10 )

In [190]:
print(f)
print(g)

tensor([[0, 5, 8],
        [5, 0, 5]])
tensor([[6, 4],
        [1, 0],
        [5, 1]])


In [191]:
# matrix multiplication
torch.matmul(f , g)


tensor([[45,  8],
        [55, 25]])

In [192]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])


print(vector1.shape)
# dot product
# dot product

torch.dot(vector1, vector2)


torch.Size([2])


tensor(11)

In [193]:
#transpose
torch.transpose(f,0,1)


tensor([[0, 5],
        [5, 0],
        [8, 5]])

In [194]:
h = torch.randint(size = (3,3), low = 1, high = 10 , dtype= torch.float32)

In [195]:
h

tensor([[3., 5., 1.],
        [2., 8., 8.],
        [4., 4., 8.]])

In [196]:
#determinant
torch.det(h)

tensor(152.)

In [197]:
# inverse
torch.inverse(h)

tensor([[ 0.2105, -0.2368,  0.2105],
        [ 0.1053,  0.1316, -0.1447],
        [-0.1579,  0.0526,  0.0921]])

## Comaprison operator

In [198]:
i = torch.randint(size=(2,3), low=1 , high = 10 )
j = torch.randint(size=(2,3), low=1 , high = 10 )
print(i)
print(j)

tensor([[2, 6, 9],
        [9, 8, 7]])
tensor([[5, 9, 3],
        [2, 3, 1]])


In [199]:
#greater than
i > j
# less than
i < j
## equal to
i == j
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

## special functions

In [200]:
k = torch.randint(size=(2,3), low = 1 , high = 10 , dtype= torch.float32)
k

tensor([[3., 1., 6.],
        [2., 8., 2.]])

In [201]:
# log
torch.log(k)

tensor([[1.0986, 0.0000, 1.7918],
        [0.6931, 2.0794, 0.6931]])

In [202]:
# exp
torch.exp(k)

tensor([[2.0086e+01, 2.7183e+00, 4.0343e+02],
        [7.3891e+00, 2.9810e+03, 7.3891e+00]])

In [203]:
#sqrt
torch.sqrt(k)

tensor([[1.7321, 1.0000, 2.4495],
        [1.4142, 2.8284, 1.4142]])

In [204]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.7311, 0.9975],
        [0.8808, 0.9997, 0.8808]])

In [205]:
#softmax
torch.softmax(k , dim = 0 )

tensor([[7.3106e-01, 9.1105e-04, 9.8201e-01],
        [2.6894e-01, 9.9909e-01, 1.7986e-02]])

In [206]:
# relu
torch.relu(k)

tensor([[3., 1., 6.],
        [2., 8., 2.]])

## Inplace operations




```
`# This is formatted as code`
```



In [207]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6768, 0.8633, 0.7390],
        [0.6987, 0.0502, 0.9962]])
tensor([[0.2513, 0.1627, 0.2390],
        [0.3454, 0.4055, 0.6040]])


In [208]:
m.add_(n)

tensor([[0.9282, 1.0260, 0.9780],
        [1.0441, 0.4557, 1.6002]])

In [209]:
m

tensor([[0.9282, 1.0260, 0.9780],
        [1.0441, 0.4557, 1.6002]])

In [210]:
n

tensor([[0.2513, 0.1627, 0.2390],
        [0.3454, 0.4055, 0.6040]])

In [211]:
torch.relu(m)

tensor([[0.9282, 1.0260, 0.9780],
        [1.0441, 0.4557, 1.6002]])

In [212]:
m.relu_()

tensor([[0.9282, 1.0260, 0.9780],
        [1.0441, 0.4557, 1.6002]])

In [213]:
m

tensor([[0.9282, 1.0260, 0.9780],
        [1.0441, 0.4557, 1.6002]])

## Copying tensor

In [214]:
 a = torch.rand(2,3)
 a

tensor([[0.7310, 0.6795, 0.4345],
        [0.9986, 0.3131, 0.8807]])

In [215]:
b = a

In [216]:
b

tensor([[0.7310, 0.6795, 0.4345],
        [0.9986, 0.3131, 0.8807]])

In [217]:
a[0][0] = 0

In [218]:
a

tensor([[0.0000, 0.6795, 0.4345],
        [0.9986, 0.3131, 0.8807]])

In [219]:
b

tensor([[0.0000, 0.6795, 0.4345],
        [0.9986, 0.3131, 0.8807]])

In [220]:
id(a)

138367740750784

In [221]:
id(b)

138367740750784

In [222]:
b = a.clone()

In [223]:
a


tensor([[0.0000, 0.6795, 0.4345],
        [0.9986, 0.3131, 0.8807]])

In [224]:
b

tensor([[0.0000, 0.6795, 0.4345],
        [0.9986, 0.3131, 0.8807]])

In [225]:
a[0][0]= 10

In [226]:
a

tensor([[10.0000,  0.6795,  0.4345],
        [ 0.9986,  0.3131,  0.8807]])

In [227]:
b

tensor([[0.0000, 0.6795, 0.4345],
        [0.9986, 0.3131, 0.8807]])